### ISSUE TITLE
Will there be a donate option?

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#108]
I find this project so usefull and i save a bunch of cash from using these lights i would probably wanna donate some towards development/beers or whatever you see fit. I'm sure other users also would contribute some aswell.

**Comment by mariusmotea** [comment]
I was thinking in the past do provide my paypal account in order to buy a real hue bridge and some Philips bulbs to try a reverse engineer for hue remote api, but in the end i decide to do everything by my own. Even if this will help me to buy hardware more easy i will feel a pressure to provide more support to persons who donate and i prefer to enjoy the full freedom.

**Comment by erazor666** [comment]
I guess its a dual edged sword with donations. I would probably donate because of whats allready here and knowing that if developers have more stuff to play with the product will be better in the end. A "no strings" donation on my behalf :)

**Comment by Mevel** [comment]
same here! great work so far! no strings attached!
