### ISSUE TITLE
After few hours are WS2812B lights unreachable in official Hue app.

### ISSUE THREAD

**Issue by Joshuant** [mariusmotea/diyHue#119]
Hello, Marius! Your project is very interesting, so I decided to implement it. HueEmulator now runs on the Orange Pi computer and reports without any problem in the official Philips Hue application. However, the problem is with light. I use the WS2812B (Neopixel) LED strip and the Wemos D1 Mini board. After restart, everything works as it should, but after a few hours, Philips Hue reports that the lights are inaccessible. However, it is possible to access the light through the web browser using the IP address. I think the problem is somewhere in a script running on Orange Pi. Of course, I use the latest version released. Do not know what the problem is? Thanks, John

**Comment by mariusmotea** [comment]
Hi John,

I will push new commit that contain improvements with light synchronisation functions. Currently when you have the Hue app opened there are send requests to lights in order to fetch the status directly from lights. It can happen to have too many requests and ESP will freeze for a few seconds. This is enough to detect and mark the light as unreachable. Update will come in a few hours, please provide your feedback.

Thanks,
Marius.

**Comment by Joshuant** [comment]
Thank you for a quick respond. I'm looking forward to your update, later I provide my feedback.

**Comment by mariusmotea** [comment]
Ok, now on develop branch i push the new update. Changes are multiple not just light synchronisation. but all are tested by me. New file can is located [here](https://raw.githubusercontent.com/mariusmotea/diyHue/develop/BridgeEmulator/HueEmulator.py)

**Comment by Joshuant** [comment]
Thanks a lot, I will test this version.

**Comment by Joshuant** [comment]
Hi Marius! At this point, it looks like it works properly. Thank you very much!
