### ISSUE TITLE
Request: Simple Virtual device/Script Support

### ISSUE THREAD

**Issue by nyetloki** [mariusmotea/diyHue#129]
I currently have 433mhz outlets controlled by a small micro controller, attached to my dockstar (armv5 Debian) via USB Serial device.

I can control the lights by sending 0 or 1 via the serial port /dev/ttyserial. I can do this via bash script or a python script.  A different string or script per outlet (my controller supports 3 and a "all on/off" code).

Can diyHue provide support for this, or does it already?

**Comment by mariusmotea** [comment]
No direct support, but workarounds are available in order to implement this
challenges:
1. manually update config to add lights, because auto discover will not work in this case - check #126 for samples
2. create a localhost webserver that receive the requests and then tell to your microcontroller what it need to do via serial device. - i provide sample python script here #28

**Comment by mariusmotea** [comment]
Sorry i forget that a user add support for 443 on/off devices, please check this https://github.com/mariusmotea/diyHue/tree/master/Lights/Arduino/Generic_ON_OFF_device_433Mhz

**Comment by nyetloki** [comment]
https://github.com/mariusmotea/diyHue/tree/master/Lights/Arduino/Generic_ON_OFF_device_433Mhz is not exactly what I had in mind. That's a ESP running code to control the lights. Mine is a pc, like #126 and #28.

Actually, #28 does exactly what I want. I'd would add:

`import serial
#change /dev/ttyACM0 to match your setup
ser = serial.Serial("/dev/ttyDEVICE", 115200, timeout=1)
time.sleep(2) #Delay for issues
ser.write("1") 
`

Any chance you can change the code for multiple lights? Honestly, this should be packaged and added to the wiki. I'm sure I'm not the only one that would benefit from this.

**Comment by mariusmotea** [comment]
> Any chance you can change the code for multiple lights?

this is simple, first argument in every request is the light id, so you can have multiple virtual virtual lights controlled by this service, only the parsing must be changed to take light argument in consideration.
ex: 
```
LightRequest: http://192.168.10.22/set?light=1&on=True
LightRequest: http://192.168.10.30/set?light=1&on=True
LightRequest: http://192.168.10.30/set?light=2&on=True
LightRequest: http://192.168.10.30/set?light=3&on=True
```
here are two devices, but one emulate 3 lights, so in total are 4 lights

your light_address must look like this:
```
        "1": {
            "ip": "127.0.0.1:8080",
            "light_nr": 1,
            "protocol": "native"
        },
        "2": {
            "ip": "127.0.0.1:8080",
            "light_nr": 2,
            "protocol": "native"
        },
        "3": {
            "ip": "127.0.0.1:8080",
            "light_nr": 3,
            "protocol": "native"
        },
......
```
The keys 1,2,3 are the lights id's locate in lights index and here i recommend to populate with states from on_off plug units, because you don't need bri, ct or color change options.

ex:

```
{
  "state": {
    "on": false,
    "alert": "select",
    "reachable": false
  },
  "type": "On/Off plug-in unit",
  "name": "Bedroom 4",
  "modelid": "Plug - LIGHTIFY",
  "manufacturername": "OSRAM",
  "uniqueid": "xx:xx:xx:00:00:xx:xx:xx-03",
  "swversion": "V1.03.21"
}
```

**Comment by nyetloki** [comment]
the:

`127.0.0.1 - - [27/Jul/2017 14:21:50] "GET /set?light=1&bri=106 HTTP/1.1" 200 -
setup bri to 106
red: 0.41568627451, green: 0.411764705882, blue: 0.403921568627
127.0.0.1 - - [27/Jul/2017 14:02:18] "GET /set?light=1&ct=297 HTTP/1.1" 200 -
red: 0.996078431373, green: 0.725490196078, blue: 0.501960784314
`

Is that just python stdout or Is it saved as a log file?

**Comment by mariusmotea** [comment]
is just stdout.
