### ISSUE TITLE
Problem with Tradfri bridge

### ISSUE THREAD

**Issue by FIFour** [mariusmotea/diyHue#130]
I have a Tradfri bridge and i cannot connect it to the emulator.
When i run the program manualy and when i try to send the Tradfri Bridge informations to the program, there's this error : 

----------------------------------------
Exception happened during processing of request from ('192.168.1.107', 54023)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "HueEmulator.py", line 1032, in do_GET
    registration = json.loads(check_output("./coap-client-linux -m post -u \"Client_identity\" -k \"" + get_parameters["code"][0] + "\" -e '{\"9090\":\"Hue-EMulator\"}' \"coaps://" + get_parameters["ip"][0] + ":5684/15011/9063\"", shell=True).split("\n")[3])
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
----------------------------------------

Can you help me ?
Thanks

**Comment by mariusmotea** [comment]
Hi,
The pair with tradfri gateway is now a little bit more complicated because of the new pair method (and because i don't use it anymore). If for some reasons this fail, it will not work anymore because it will not allow to pair again with same user. 
Try the following:
1. ensure coap-client-linux file  is present and has execution permission
2. replace in HueEmulator.py the registration name. Search and replace of the word "Hue-EMulator" (case sensitive) with any other name (FIFour-hue  for example).

**Comment by FIFour** [comment]
Hi,
coap-client-linux is present and have the permission and i tried to replace the registration name and there is the same error

**Comment by mariusmotea** [comment]
manually execute 

`./coap-client-linux -m post -u "Client_identity" -k {security_code} -e '{"9090":"Hue-EMulator"}' "coaps://{gateway_ip}:5684/15011/9063"`
where {security_code} is the security code and {gateway_ip} the ip of the gateway
Paste here the output.

**Comment by FIFour** [comment]
Here's the result

v:1 t:CON c:POST i:bb4d {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 4 bytes cleartext
4.00

**Comment by mariusmotea** [comment]
something is not ok, did you double check the ip and security key? Try to change the username ("Hue-EMulator") with something else, maybe the account was already created.

**Comment by FIFour** [comment]
I entered exactly the same command (with the same ip and security key) with a different username and i have this result

v:1 t:CON c:POST i:d2d3 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 50 bytes cleartext
{"9091":"0L0gAzxZacXATKvd","9029":"1.2.0042"}

**Comment by mariusmotea** [comment]
this is a successful pair, i believed you received "No JSON object could be decoded" because user was already created. Two things can be done here.
1. Perform search and replace to change the username again in all functions in order to provide me the root error of pair process.
2. You already have an user created so you can manually edit config.json file and manually populate the fields. Check first if the fields are already populated.
 - config.json -> "tradfri" -> "psk" = "0L0gAzxZacXATKvd"
 - config.json -> "tradfri" -> "ip" = "192.168.x.x"
 - search and replace for "Hue-EMulator" username in script with the username you used in this pair process. Be aware that this username is hardcoded in multiple functions.
 - perform lights search in hue application to discover the lights.

**Comment by FIFour** [comment]
I searched and replaced "Hue-EMulator" and it works now.
Thanks so much

**Comment by mariusmotea** [comment]
Great.
