### ISSUE TITLE
Auto restart when wifi is not available

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#142]
I've had some power outages recently and I found some issues worth looking at:
1. If my Orange Pi turns on before my router, it won't start the hue server properly. Only way to establish hue bridge is with the lan/internet already running before I turn on the Pi. Also if the internet/router fails for any reason, and turns back on again, the Pi won't reconnect and I have to restart it.
2. It seems like the lights can't connect to wifi when it's turned on after the lights. Only way to reconnect is to restart the light. Would be nice if it was handled automatically. Like if there's no wifi conenction, try to reconnect after say 10 minutes.

**Comment by mariusmotea** [comment]
1. add this line to systemd file for a 10 - 15 second delay `ExecStartPre=/bin/sleep 15`
2. add this line in lights sketch
```
  WiFiManager wifiManager;
  wifiManager.setTimeout(30);
  wifiManager.autoConnect("New Hue Light");
```
Because the router boot process require more time, wifi manager will enter in configuration mode and remain there even if the wifi network will be shortly available. By adding that timeout the wifi manager will exit from configuration mode and will reconnect to wifi network. I don't recommend to setup this to a lower value, in case you need to reconfigure the light i don't believe it will be possible in less than 20 seconds. If you use this with the function to update the state of all lights on boot, ensure you delay more the service start from point 1, because lights will be reachable after about 30 seconds.

**Comment by mcer12** [comment]
Thanks will try out when I get home. From the docs on wifiManager I think the timeout shouldn't delay the lights, it just resets the config server after selected time?
> Sets a timeout before the webserver loop ends and exits even if there has been no setup. Useful for devices that failed to connect at some point and got stuck in a webserver loop.
If so, it's just what I needed. Do you plan on addin this to future versions?

**Comment by mariusmotea** [comment]
In my tests the timeout has delayed the light, because in webserver loop there is no attempt to reconnect on wifi network, even if is available again. After it will exit from this loop there are attempts to reconnect, but i don't know exactly the interval.

> Do you plan on addin this to future versions?

Yes but i believe i will added with 180 seconds timeout to avoid complications for beginners that will not see the "New Hue Light" SSID and will not know why is not working. Is still much better to have the light reconnected after 3 minutes, than to require reset.

**Comment by mcer12** [comment]
Yes of course you're right, the light will have to go through one server loop before it tries to reconnect. I agree, 3 or 5 minutes is OK and also gives more time for configuration. I would leave this thread open for others. Feel free to close it when you release it :)

**Comment by erazor666** [comment]
I've also had some power outages recently and, if the esp/wemos whatever boots before the emlator you need to restart the light to make it work after emulator is up and running.

**Comment by mcer12** [comment]
@erazor666 Fix above should solve it for you

**Comment by erazor666** [comment]
I guess this should be commited to all the lights .ino files in the future, this is really a handly little fix and should not mess anything up in any way as far as i can see.

**Comment by mariusmotea** [comment]
yes, this is the plan, but i did not find time so far to do this.
