### ISSUE TITLE
Issues with IKEA Tradfri Gateway

### ISSUE THREAD

**Issue by bhagyas** [mariusmotea/diyHue#147]
Tried this on macOS with limited success.
Installed nmap using `brew install nmap` and used `coap-client`.

Discovered the following issues,
- There is no option to change the bulb type (Dimmable/White Spectrum/Colour Spectrum).
- Colour reproduction is inaccurate.

**Comment by mariusmotea** [comment]
> There is no option to change the bulb type (Dimmable/White Spectrum/Colour Spectrum).

True, but manual mode is available. Edit config.json and replace the bulb modelid and type with the proper values (examples you can find in HueEmulator.py script, in case you use wifi bulbs, then the proper virtual light will be created).

> Colour reproduction is inaccurate.

If you are referring to color temperature, then the issue is the exposed api (if you can call it api)  that is very limited. Basically i'm using the 3 scenes stored by default on bulbs (cold white, warm white and neutral). More options are available with conbee stick or rapsbee module for raspberry pi.
