### ISSUE TITLE
Script Exit

### ISSUE THREAD

**Issue by Martin-Gardner** [mariusmotea/diyHue#164]
I get the following error when starting the python script

Config loaded
register new TRADFRI remote control
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1502, in <module>
    scanDeconz()
  File "./HueEmulator3.py", line 806, in scanDeconz
    bridge_config["sensors"][new_sensor_id] = {"config": deconz_sensors[sensor]["config"], "manufacturername": deconz_sensors[sensor]["manufacturername"], "modelid": deconz_sensors[sensor]["modelid"], "name": deconz_sensors[sensor]["name"], "state": deconz_sensors[sensor]["state"], "swversion": deconz_sensors[sensor]["swversion"], "type": deconz_sensors[sensor]["type"], "uniqueid": deconz_sensors[sensor]["uniqueid"]}
KeyError: 'swversion'

The script then exits.

Any ideas?

**Comment by mariusmotea** [comment]
Hi,
What kind of devices you paired with deconz? I put "swversion" as mandatoryfield, maybe my fault because there are cases when some sensors don't have this field, or there is a bug in deconz. If you created logical sensors from deconz then delete them. In some cases you need to restart deconz after successful pair with the sensor, or wait more to have all the details available. To find the answer  you need to fetch the deconz config. search in config.json of emulated bridge the username to connect to deconz ( deconz => username). After you have the username use curl to get the config:

`curl http://127.0.0.1:8080/api/{username}
`
or to get just the sensors list:

`curl http://127.0.0.1:8080/api/{username}/sensors`

**Comment by Martin-Gardner** [comment]
TRADFRI remote control does not seem to be returning software version. The wireless dimmers do and the hue remote control does as well.

**Comment by mariusmotea** [comment]
Please upgrade the firmware first. I did this with tradfri gatway. Last firmware starts with 1.2.xxx.
I have 11 tradfri remotes, all working fine. Issue is more deconz related, maybe you need to open issue also on their repo.

**Comment by Martin-Gardner** [comment]
Looks like I can not read any attributes from the control anyway. I might need to remove and re-add the control. 

Cheers,

Martin
