### ISSUE TITLE
diy hue changes timezone of normal bridge? [edited]

### ISSUE THREAD

**Issue by Wqrld** [mariusmotea/diyHue#166]
after intstalling your diyhue package and setting it up for my own ws2812B light my parents are telling me that lights randomly turn on or do not respond to app commands sometimes when the app is connected to the normal bridge. Could this have something to do with diyhue? There might be something up with timers for the lights randomly turning on but the lights not responding to the app isn't normal. I myself have only found problems when repeatetly flicking the on/off button on the fake hue which makes it stop for like 1 second.

**Comment by mariusmotea** [comment]
Emulated bridge talk with real bridge only when there are actions performed or schedulers triggered. You can check the config.json for schedulers, if this is empty and nobody performed any actions, then the issue must be in other place. Ask your parents to note the time when such incident happen and then check in syslog to see the events at that time from hue-emulator. I faced a strange behavior with an Android app that run in background and at some strange times change the state of the lights in one room. Unresponsive zigbee lights can be caused by channel conflict with the wifi networks. Scan the wifi spectrum and set the zigbee channel where you believe the interference will be minimum.

**Comment by Wqrld** [comment]
The problem with schedulers was that time old bridges timezones were set to new zealand for some reason. I asked my father again and he didnt know anything about non-working switches so i guess that never wass a issue. I will leave this issue open as it might be the fake hue setting the timezone wrongly?

**Comment by mariusmotea** [comment]
Ensure the timezone is correct on the device where you run the hue emulator. You can fix the zone manually in config.json to reflect the zone where you live. By default is my zone Europe/Bucharest, if you have New Zealand i guess some application changed this (they are able).

Marius.
