### ISSUE TITLE
Fiecan lights flash

### ISSUE THREAD

**Issue by pickeld** [mariusmotea/diyHue#26]
hey,
Fiecan Led Bulb are the cheapest light i found. and i bought few of them.
these lights using the ColorDream app as you mentioned in the readme file.
i have electronic skills i gathered over the past three years. and i would really like you to help me flash these bulbs. 
i attached [link to the pictures](http://imgur.com/a/HU2eW) i took of the bulb, i cant find the RX or the TX . 

need your help here.
thank you.

**Comment by mariusmotea** [comment]
Hi,
I fail to flash these bulbs with wires but i believe this is because i put gpio16 to ground instead of gpio0 (in order to boot esp8266 in flash mode). I will come back tomorrow with a picture of PCB and i will try again to flash the firmware with wires. I remember the hard part is to reset the device by connecting RST to ground for a moment exactly when firmware upload is starting. If you have an Wemos D1 mini pro you can move SPI flash chip just to upload the new firmware, then solder back.

**Comment by pickeld** [comment]
thank you
im really into crack this problem. just couldnt find the rx/tx pins. 
what about the SPI of esp-01?
will it fit?

looking forward to hear from you tomorrow.
have a great day

**Comment by mariusmotea** [comment]
In this morning i made a fast photo and measurements, hope i did not made any mistake. Here is the  [image](https://drive.google.com/file/d/0B1idIVxXCsjxYkttaEFEWldqUkU/view?usp=sharing) . When i will arrive home i will put the SPI chip back and try to flash with external adapter. On Wemos and nodemcu boards the serial adapter chip perform some extra actions like pull GPIO0 to ground and a quick RST to GND for a device reset before the upload to start (you have 3-5 seconds to reset the device before to receive the error that firmware upload failed, so you must not be so fast). Plan B is to flash the SPI chip out of the board, looking at  esp-01 pictures this seems to be fine for the switch.

**Comment by pickeld** [comment]
hey @mariusmotea thank you for sharing a possible solution,
you made my day please update if any any.

have a nice day!

**Comment by mariusmotea** [comment]
Good news!
I manage to flash the firmware of one bulb with external serial adapter and it seams is more simple than i believe. You need to connect only TX,RX,GND and VDD to serial adapter, and connect GPIO0 pin to one of the many ground holes from PCB. You don't need to perform the quick reset action, there is a combination of one capacitor and one resistor that will perform automatically. Picture of my setup [here](https://photos.app.goo.gl/hgk63Dz4KbuVODc53)

**Comment by pickeld** [comment]
wow thank you!!! good job 👍 👍
awesome!

**Comment by krulkip** [comment]
Where can you get these bulbs please

**Comment by mariusmotea** [comment]
You can find them on aliexpress, but i enjoy more the 8w RGB-CCT MiLight bulb converted to esp8266 because is able to reproduce better the colors, and is more powerfull.

**Comment by krulkip** [comment]
Yes the milights i know. I also developed my own pcb's. Still could not find Fiecan bulbs on aliexpress. Can you share link please.

**Comment by mariusmotea** [comment]
i buy them from here: https://www.aliexpress.com/item/AC85-240V-5W-7W-9W-RGBW-WIFI-LED-Bulb-Light-Colorful-Dimmable-LED-Light-Support-IOS/32785628736.html?spm=a2g0s.9042311.0.0.0WVS4t

**Comment by StevenTLBF** [comment]
Forgive me for I'm slightly new to this project and had trouble understanding the wiring provided [here](https://photos.google.com/share/AF1QipOnDi5-AyYeSwtcYvn94DcCWtnt_fmkJaZrWOaJ8PTOlDX0peovIZ3xYkOMIWpEhA?key=NXNycjVIRmlGT3c0a1lBYWNWdF9LSFpKN1Z0QWVn)  Is [this](ESP8266 ESP-12E ) the esp8266 board you're using? How did you wire this to the feican? A better image demoing the wiring would suffice. After flashing the firmware onto the feican, did you just desolder the connections to the esp8266 or leave it? The firmware is provided in this repository correct? I do apologize for I am rather new to this. I sincerely appreciate any help you can offer!

**Comment by mariusmotea** [comment]
Hi,
The board you see is the original that come with Feican bulbs, is looking ugly because i de solder and solder back a few times when looking for a way to flash it. If you want to buy the bulbs you will only need the serial adapter to flash the firmware. Look on this [image](https://drive.google.com/file/d/0B1idIVxXCsjxYkttaEFEWldqUkU/view?usp=sharing) to see the pins labels. You need to connect gpio0 to ground, and VDD,GND, TX, RX to serial adapter. That's all. I don't believe you will be able to perform future firmware upgrades with Arduino OTA because of poor flash capabilities. I made lot of firmware tests so in order to solve this problem i replace the flash with the one from a broken ESP-12E board.

**Comment by StevenTLBF** [comment]
Thank you so much for the response! I sincerely appreciate it. 

Where I am stuck is connecting the bulb to the serial adapter to flash the firmware. For example, If I solder one end of the wire to TX on the Feican, what do I solder the other end of the wire to on the serial adapter? TX connects to what on the serial adapter? RX connects to what on the serial adapter?etc etc. 

Also, what serial adapter are you using? If it isn't too much to ask, could you provide a link? 

I appreciate you help! Thanks so much!

**Comment by StevenTLBF** [comment]
Any ideas?

**Comment by mariusmotea** [comment]
Hi,

You can use any 3.3v serial adapter. On my pictures you can see that i use the one from nodemcu board (original esp serial pins are connected with some resistors that i remove in order to avoid the conflict). On serial adapter you have Vdd, Gnd, Tx AND Rx. Connect vdd to vdd, gnd to gnd, tx to tx, rx to rx and gpio0 to ground. If is not working swap rx and tx pins (rx to tx and tx to rx).

**Comment by StevenTLBF** [comment]
Thank you so much for the response! I will order some parts and get to it. One very last question, and again I apologize for this is rather new to me. What is "VDD" exactly? Is it the pin labeled "VIN" or "3.3"? Thanks! and this just connects to the 3.3V pin on the bulb? Thanks again!

**Comment by mariusmotea** [comment]
Yes, VDD is the 3.3v pin. You can power the ESP also from serial adapter that output 3.3v (if you use the proper serial adapter that work with 3.3v) so you must not power the bulb from 220v to start the flash process.
