### ISSUE TITLE
Lights changing one by one

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#275]
I added more Lights to my room and noticed this strange effect:

Currently i have 2 Ikea RGB Lights (deconz) and 3m SK6812 Stripes (3 virtual Lights)

When i change the color, firstly one of the Ikea lamps gets changed, then after a short delay (id say 500ms) the second one changes. Than the other 3 SK6812 Lights change also with a slight delay.

Is there some way to address the lamps in a group simultaneously  (cause it seems they are update one by one)?

**Comment by mariusmotea** [comment]
Hi,

For Deconz i don't have any solution, but ESP must change fast if there is proper wifi connectivity. To improve this aspect i made some improvements how light requests are sent. This don't do miracles but in case of different devices it will send the first lights requests instant to all ip's and then will continue with extra lights on same device. I don't believe you have this update because of how you described the behaviour. Now in your case it must be one IKEA + 1 virtual SK6812 lights get update instant and right away the second IKEA bulb and other 2 virtual  SK6812 lights must be updated.

**Comment by oleg2204** [comment]
Okay. I updated the last time 2 weeks ago. Will update today after work.

Thx.
