### ISSUE TITLE
Working On Non-ARM Based Architectures?

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [mariusmotea/diyHue#286]
Hi,

Not really an issue per-se - More of a question. I can see that this project is primarily targeted at using a Raspberry PI or similar architecture to run this service.

It it architecture agnostic? Can it run on x86 and x64 platforms?

I am hoping to run this on an existing Ubuntu Server instance that I have running.

Thanks,

Daniel

**Comment by dr-hackepetzi** [comment]
I have it running on a x64 ubuntu in an LXC Container.
If you have a Python Interpreter it should working. I think so.

**Comment by mariusmotea** [comment]
Hi,

Only issue is if you want to run it on Windows x64. On Linux (Ubuntu) it will work fine. Focus is on RaspberryPI because with it you can build similar device like Tradfri Gateway or Hue Bridge.

BTW, one thing is currently missing from automatic installer, if you want to use sunrise/sunset routines you will need to install python astral package by yourself. Will be nice if you will provide feedback with official hue application, as currently some users complain they cannot pair the official hue application with hue emulator and i was not able to replicate the problem #248

Marius.
