### ISSUE TITLE
configuration Emulator with ESP8266

### ISSUE THREAD

**Issue by elmo25674** [mariusmotea/diyHue#29]
Hi, can someone please help me with the configuration of the Emulator?
At the Moment, the ESP8266 and Emulator is running.
I can connect with the Hue App to the Emulator, but how can i connect the ESP8266+ WS2812 LED with the Emulator(how to configure), that i can see the Light in the Hue App.

Thanks
Christian

**Comment by mariusmotea** [comment]
Hi, the steps are these:
1. connect light to local network. To to this you must connect first to wifi named "New Hue Light", then open in browser 192.168.4.1 and setup the wi-fi password from GUI
2. From hue application perform a light search. Ensure you have nmap package installed, otherwise the search will fail.

**Comment by mariusmotea** [comment]
I guess this was solved.

**Comment by elmo25674** [comment]
Sorry for late answer, nur i was so busy in my job at the moment. After i installed the nmap package i found the LED and now i can controll them.
Thank you for your help.
Christian

**Comment by elmo25674** [comment]
Hello,
i changed the Rpi and installed everything new. Now i can not find the Lights in the app.
I installed nmap on my Phone, but i cannot find the Lights in the app.
Connection to the Emu_Bridge is ok. 
i´m Sure i do something wronge with nmap.
Please help.

Christian
