### ISSUE TITLE
Motion Sensor

### ISSUE THREAD

**Issue by dr-hackepetzi** [mariusmotea/diyHue#304]
Hy,
what kind of mosfet are you useing in your motion sensor shematic?
And what does this little arrow on the right bottom corner under the 500K mean?

Greetings from Vienna

**Comment by mariusmotea** [comment]
Hi,

I propose to wait a little bit because i plan to refactor entire code for the motion sensor. The current approach is way too complicated at software part and it is because i made the sensor to send the light data every 30-40 minutes and after there is no motion in 30 seconds to send request that announce this. The problem was that on ESP deep sleep wake up there are interferences that trigger the PIR and i was not able to know if the esp was wake up because was triggered or because it need to perform another task (send light data of announce there is not motion). Another problem is that light level data measured change while the batteries start to be low.

The new approach will be this:
 - sensor will wake up and announce motion only when PIR is triggered.
 - bridge emulator will start a new thread in background and when there will be no motion in 30 seconds will automatically change the sensors state to `motion: false`
 - there will be no photo resistor to measure the light data. We will relay entirely on internal daylight sensors to know when outside is light or not. 


The transistor in the diagram is not mosfet but NPN, so you can use any NPN transistor that you have home (i use SMD because are smaller). The 500K resistor with arrow is variable resistor used to optimise the level of light when the status will change to "dark"

**Comment by cheesemarathon** [comment]
Question answered.
