### ISSUE TITLE
No lights found with Hue App 3.3.0

### ISSUE THREAD

**Issue by xfader2018** [mariusmotea/diyHue#326]
Hello,

I'm unable to find light in the latest official Hue App. (or any others)
I have a ledstrip LST001 that used to work in the past with this setup.
When I manually start HueEmulator3.py is see this output when I do a search in the app:

```
192.168.2.130 - - [18/Aug/2018 00:20:16] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
{'hue': 'strip', 'lights': 1, 'mac': '3c:9e:1c:94:1:60', 'modelid': 'LST001'}
192.168.2.60 is a hue strip
Add new light: Hue strip LST001
ip 192.168.2.60 is unknow device, 'LST001'
registration fail, is the link button pressed?
```

It fails registration and the app doesn't show the light at all.
It was previously connected to another hue emu bridge but that machine is no more.
Can that be the reason?

What can I do to find and connect this light again?

Thanks in advance!

**Comment by mariusmotea** [comment]
`LST001` is deprecated, you need to flash again the esp with new firmware that will expose LST002 and modelid. If you don't use hue entertainment you can perform search and replace in HueEmulator3.py file and replace LST002 with LST001 and then it will work. After light import you can revert this change because this function is used only on import.

**Comment by xfader2018** [comment]
Thanks you! That made it work again.
I was unable to reflash it as it it soldered on a esp01 in a box.
But changing it in script did find it again.

Thanks for the quick reply and for this awesome piece of code.

**Comment by mariusmotea** [comment]
Don't forget the lights have Arduinon OTA built in. If flash size is not so small you can flash it over the air.

**Comment by xfader2018** [comment]
Yeah I tried that but I think this ESP01(1M) is too small.
Arduino IDE gave not enough space error.

**Comment by xfader2018** [comment]
Hello,

May I asked you a question about the diyHUE?

I'm using a WS2812B ledstrip that has just 3 wires (plus, minus, data). What lightsCount should I use? 3 or 1?

Also, what does #define transistionLeds do? I'm using a strip with 181 leds on it, do I need to change this value?


Thanks in advance!
BiTRiP

**Comment by mariusmotea** [comment]
`lightsCount` is the number of virtual lights of that strip. # is not good for you because 181 don't divide 3, it may work anyway but better declare 180 leds to avid any issue.

`transistionLeds` is the number of leds that will made the transition from the color of one light to the color of nearby light. This create a nice effect that made very hard to identify the point where the two lights are splited.

**Comment by xfader2018** [comment]
Thanks for your explanation.

Ok, I can shorten the strip to 180 but why can't I just use lightscount=1 and pixelcount=180 or 181?
With lightcount=3 it will find 3 lights in app, right?

Don't know exactly the meaning of it.

**Comment by mariusmotea** [comment]
Yes you can put also one light with 181 leds, but if you will use scenes or hue entertainment it will be a shame to not put at last 2 lights on this strip.

**Comment by xfader2018** [comment]
Thanks for clearing this up! 😀

Cheers m8.
