### ISSUE TITLE
 Use arduino uno instead of a ESP8266

### ISSUE THREAD

**Issue by JDF1** [mariusmotea/diyHue#328]
Hello everyone,
First of all, great project!

I'm new to github. I hope this is the right way to ask this question.

I've a question, is it also possible to use a aruidno uno with a hanrun (HR911105A) ethernet shield for as a ws2812b led controller?

I have a couple of these ledstrips in the garden, but there is only a ethernet cable and no WiFi back there. 

I try to edit the WS2812BHueStrip arduino code to use the Arduino uno, but all compile erros.

Do someone have succesfully compiled the WS2812BHueStrip code for a Arduino Uno?

Regards,
JDF

**Comment by mariusmotea** [comment]
I believe the complexity of doing this is high and is much simpler to find a way to have wifi there, instead of adding support for arduino UNO. If you however want to give a try you need to do find libraries to start an webserver on uno that can parse http get variables. Other functions for converting the colors, etc i believe will work.

For example if the webserver receive GET requests on `/set?light=1&on=true` it will turn on the light `/set?light=1&bri=254` it will turn the bri to maximum level, `/set?light=1&x=0.533&y=0.3211` must apply the conversion xy function that will return the rgb values for your strip.

**Comment by JDF1** [comment]
Hello Mariusmotea,

Since i' m not a good programmer, I'm going to install a accesspoint and use the ESP8266.

Thank you for your fast response. 

Regards,
JDF
