### ISSUE TITLE
Feature Request - Increase light limit for entertainment areas

### ISSUE THREAD

**Issue by cheesemarathon** [mariusmotea/diyHue#358]
Is it somehow possible to increase the limit of lights that can be added to each entertainment area? Maybe this can be achieved by creating fake groups that the hue app sees as one light. That way you could add as many lights to this group as you want and that would only count as one light in the entertainment area. All these lights however would always display the same color.

**Comment by cheesemarathon** [comment]
I think we need to test what happens when you manually add more than 10 lights. If the system is still usable then we could create a UI component to easily add more lights.

**Comment by mariusmotea** [comment]
I don't believe the limit of 10 lights is really a problem because 10 lights in a room must be enough. I test Entertainment with 9 lights and i place lights almost in all places in the test virtual room. It can be possible to have more than 10 lights in a room, but we need to fix this problem maybe by finding a way to sent same frame to multiple lights that are nearby, or automatically calculate the color mix of two lights for a 3rd light that is in the middle of the two. For strips we can lower the number of virtual lights and use a bigger number of transition leds to obtain the same effect. My 2016 Macbook have the cpu overloaded by HueSync with just 3 ligths, if we want to use more than 10 we will need powerfull hardware.

**Comment by cheesemarathon** [comment]
Make sense, in that case I'll close this for now as other improvements need to be made before this is possible.

**Comment by KevinConsen** [comment]
I'd like to come back to this...

I really would appreciate a "group" function that acts as one, allowing more than 10 devices to be controlled by the Sync Box. F.e. I have a Hue Centris 4xGU10 in my living room, which count as FIVE lights. but on my ceiling it's just "one" to me. being able to group would provide more options for me to group both sets of spots, or all four and have the strip be separate, or just one big light. whilst using my Play bars for accents, etc.

**Comment by mariusmotea** [comment]
Hi!

I personally don't find a simple way to implement this. Currently the entertainment protocol is limited by the message frame size, and the app's know this so will not let you configure more lights in the entertainment area. The frame contain the light id and light data and is not related to a room/group. Only way may be to manually alter the code and match a certain light id to multiple lights id's but for this you need low level knowledge
