### ISSUE TITLE
Set Hue groups from Hue hub

### ISSUE THREAD

**Issue by freddebo** [mariusmotea/diyHue#375]
I just got a Philips Hue hub and synced the hub with the software and it works fine. But I would like to have the option to set brightness or on/off as group like the original hub. 
Now the lights takes 1 s for each lights to turn on, one by one, not as a group. Is it possible? The emulated led-list works fine with that and also from the original hub.

Thanks!

**Comment by mariusmotea** [comment]
Is complicated to synchronize the lights from emulated bridge and original bridge. Normally the delay must be 100-200 ms from one light to another, did you tried to change the zigbee channel, maybe it is affected by near wifi channels.

**Comment by freddebo** [comment]
Yes but isn't it possible to import the group/room from the original hub? In Home Assistant they have a group light that is exactly this. A light as the whole group and every light is synced together at the same time.

**Comment by cheesemarathon** [comment]
Ok so you had two issues here:
1. Switching light groups on the genuine hue bridge is slow/laggy
2. Can we add support for importing existing groups from the genuine bridge

Is this correct? Is this a feature that can be added @mariusmotea

**Comment by mariusmotea** [comment]
To have a proper solution that will work for most of the users we don't need to import the groups. We need a smart solution that will identify if the local lights from emulated bridge are also members of original bridge group. To do this on current structure is not easy because on group request the light state is sent to all lights from that group using light request function. Filtering for light types is done by this function and is already too late to apply this smart engine, as the split was already made.

**Comment by cheesemarathon** [comment]
Is this something that could be added after/during the code refactor?

**Comment by cheesemarathon** [comment]
I'm going to close this for now as it can't/wont be added yet. However, I have added it to the suggested features project board so we remember to add it when possible.
