### ISSUE TITLE
define rx to pin2 

### ISSUE THREAD

**Issue by bennigro** [mariusmotea/diyHue#414]
hi..

i have a problem 

i have  a  ESP-01S RGB LED Controller Modul
![htb1ldqvcvqs8kjjszfeq6a9rpxam](https://user-images.githubusercontent.com/10393449/46905923-dece2d80-cefa-11e8-84a2-c9744d560495.jpg)

but when i upload that firmware on a esp8266 it dosent work 

i think its the rx/tx the controller works with pin 2

i hope you can help me how to change that to pin 2 

with the example of Neonpixel it still work and they use pin 2

**Comment by mariusmotea** [comment]
You don't provide enough informations and that module don't help. Rgb sketch use 3 pins for evey color, only neopixels use just one pin, but that cannot changed very easy.

**Comment by bennigro** [comment]
Look it’s a rgb ws2812b Controller and it work with pin 2 on a ESP8266 and on diyhue works with rx but it doesn’t work for that controller. I have try a define rx to pin 2 but that doesn’t work :( 

I need a change from rx to pin2

**Comment by mariusmotea** [comment]
For esp8266 the neopixel bus works by default on rx pin because this is the only pin with dma hardware support. There is an workaround but is not recommended because wifi intrerupts can add delays witch may broke the communication. I believe the simplest way is to intrerrupt the current gpio2 pcb contact and solder a small wire to rx pin.

**Comment by bennigro** [comment]
It’s a good idea thx

**Comment by bennigro** [comment]
ty it work 💃

**Comment by mariusmotea** [comment]
Perfect!
