### ISSUE TITLE
LIVARNO LUX support

### ISSUE THREAD

**Issue by mgrandl** [mariusmotea/diyHue#433]
Would this at all be possible with LIVARNO LUX lamps? They are basically a german discounter hue, directly controlled by Wifi 2.4Ghz

You can't really find a lot about those lamps, but their price is just too tempting. I think I'll get one and try it out.

https://www.lidl.de/de/livarno-lux-led-leuchtpanel-mit-farbtonsteuerung/p283149

**Comment by cheesemarathon** [comment]
Without some form of API this is not possible. I'm afraid we just don't have the time or money to reverse engineer every bulbs communication protocol. I had a quick google but couldn't find much out about these lamps. If your able to find out more info on them and/or an API then we can re-open this and take another look.

**Comment by mgrandl** [comment]
@cheesemarathon yeah that's what I thought. Thanks anyway though!

**Comment by mariusmotea** [comment]
in 90% cases lights with remote control can be converted very easy to esp8266. I recently purchase [this panel](https://www.lampe.de/brilliant-abie-deckenpaneel-g90320-05.html) without to know what controller it has. In less than 30 minutes i was able to control it from Hue app.

**Comment by mgrandl** [comment]
@mariusmotea can you point me to any resources on how you did this?

**Comment by mgrandl** [comment]
I might just get those instead, because they also seem to be very cheap.

**Comment by mariusmotea** [comment]
I already mount it, let me see if i can made new pictures. To resume there is a dedicated board for the original remote communication that can be removed with solder iron. On this board there is labeled also the pinout, there is VDD(3.3v), GND, R,G,B,CW and WW. i solder one Wemos D1 mini, i did not care about the leds pin order because i fix them from software, just VDD and GND are important. I made something extra but i don't believe is necessary, i replace the 3.3v power supply witch is also a small dedicated board soldered on main board. I did this because i have some 3.3v power supply already home that prove me to be reliable.
