### ISSUE TITLE
Xiaomi Philips Light Support

### ISSUE THREAD

**Issue by VerseLLC** [mariusmotea/diyHue#453]
I've got a few Xiaomi Philips lights on the way from China, (the bedside lamp and the wisdom lamp).

It would be awesome to see support for the philips lights since it seems to be at least a little similar to the yeelights and other Xiaomi lamps/lights.

Any interest in this besides myself?

[https://github.com/rytilahti/python-miio](https://github.com/rytilahti/python-miio)
[https://github.com/syssi/philipslight](https://github.com/syssi/philipslight)

**Comment by mariusmotea** [comment]
It must be possible, but somebody with the bulbs and time need to implement it.

**Comment by cheesemarathon** [comment]
Ok, so I'll close this and add to the projects list. This can only really be implemented by someone with the bulbs to test with.

**Comment by Ashram56** [comment]
Good morning,

I can test it, but I can't really program it :-) Turns out I realized after installing diyhue that these lights (I have two Philips Ceiling) require special support, as opposed to other Xiaomi lights.

**Comment by mariusmotea** [comment]
I just google a little bit for some documentation and i don't like what i see. Most of the websites are saying that a token need to obtained, so it looks complicated for me. Not sure if they can be controlled using only the LAN network.

**Comment by Ashram56** [comment]
Yes you need to recover a token, which I believe is a crypto key used to communicate with the device. Jeedom plugin for Xiaomi also requires the token to operate (and the plugin operates through the local lan as far as I can tell).

The link provided in the first message: https://github.com/syssi/philipslight seems to operate under the same principle, but for Home Assistant instead of Jeedom.
