### ISSUE TITLE
Question: Is a CC2531 USB supported?

### ISSUE THREAD

**Issue by crashniels** [mariusmotea/diyHue#481]
Just asking since i just recently stumbled across this and I didn't seem to find anything about this USB. Only something about Deconz which probably requires the special raspberry module.

**Comment by Mevel** [comment]
Deconz is the software providing a websocket which diyhue can connect to and get sensor and light information from. Zigbee devices. Software and hardware are from Dresden electronics. The special raspberry Modul you mention is the conbee or raspbee module. To answer you question: in order to make the cc2531 work, you also need a some software to provide the information to diyhue. Hope that helped.

**Comment by crashniels** [comment]
Thanks for your reply. Yes that helped me a bit. That means i would have to wait for someone to implement zigbee2mqtt which uses this USB to detect the zigbee devices. 
Someone already asked and they said they might consider it in the future. Can't wait for it to happen since this project looks really amazing. 
https://github.com/diyhue/diyHue/issues/83#issuecomment-465593050
