### ISSUE TITLE
Questions to the author

### ISSUE THREAD

**Issue by ynk** [mariusmotea/diyHue#60]
Hi,

I've been around your project for 3 days now. I've been looking at your youtube videos and this repo and i think i've read _all_ the code produced here. It's a _very_ interesting project, the strategy to proxy the hue bridge is clever and it works pretty straightforward. If I interpret everything about this project right, the idea is that you force the hue app on your phone to connect to your raspberry pi... so... you are reverse engineering the philips hue bridge, and at the same time you are maintaining  a rewrite of it.

Based on that assumption :

1. Aren't you afraid of the consequences whenever Philips brings changing ?

2. For multi compatilibity, you basically flatten all the other bridges api to the hue api so you can control everything with the hue app. But then, you will also need to maintain all the apis to all the devices to which your code is compatible with. Again, I think there are some concerns about maintaining this codebase, don't you think ?

3. As you add more and more lines of code, the readability of the code becomes very difficult. I believe it's easy for you because you iterate (very _very_ impressively) fast... But even with my skillset, I'm not capable or _even willing_ to contribute to that project (no offense). I've been spending a night reading at this 1200 lines of python and can't figure out half of it... Are you gonna rewrite/clean the code so others can help you maintain it ?

4. Last, but not least. The amazon devices (and other voice assistants) relay on uPnP to discover all the bridges of your home, and that's how, when you create groups on your hue app, you can turn them on/off with Alexa. Do you plan on maintaining the uPnP side of the hue bridge as well ?

Thanks for the good work, it looks amazing in my living room.
I just wished i could help.

Sincerely,
Julian

**Comment by mariusmotea** [comment]
Hi Julian,

1. New releases of hue api just add small changes, usually more futures and are very simple to implement if are necessary. Also i'm not focused to use the most recent api if i don't see any benefits. If Philips want to make all emulators to not work anymore for sure they can do this by adding some checks via remote api (not public) but i don't believe that what i did here is a threat to their business.
2. Yes, here things get more complicated. For example i start to not use anymore the Ikea Gateway and i control the IKEA lights from Raspbee module. If new IKEA firmware update change current api, then will be hard for me to setup back the IKEA Gateway and pair some light. I also don't use MiLight Hub anymore, but the developer keep track of changes via tags/versions, so in case of api changes, you can use the previews version until i will find some time to implement the api changes.
3. I try to improve myself, my daily job is devops not developer. I have some php/mysql skills and the first version was write in php and mysql, but then i found that it is not suitable for this project and i switch to python. I can say that i learn python while writing this, so is very normal that an experienced python developer will see lot of bad practice in this script. My primary focus was to made this to work, then to be easy readable. I plan to add more comment lines.
4. Is mandatory for me to support upnp discovery in order to have a big compatibility with hue devices and applications. One of my problems is that i cannot have all hue compatible devices to test the upnp discovery (also i don't own an original Hue Bridge to sniff) and i cannot invest in new devices if i don't believe that i will use them. For such devices I am counting on users logs to see what did not go right.

Marius.

**Comment by cad435** [comment]
just a quick question, cause a NRF24L01 module is on my way, and a Milight already arrived:

Wich version of the MilightHub shoukd I use, cause you mentioned newer versions are not tested?

cad435

**Comment by mariusmotea** [comment]
99% chances that the last version will work. when i performed the tests i believe the version was 1.3 . My experience with milight hub is this:
 - will work out of the box but with a small delay (esp8266 packet receive + NRF24L01 transmitter add extra delays)
 - no two way light synchronization (if 2.4ghz transmission will fail the status on application will show that the bulb state was changed. changes from 3rd party devices (remote, webgui) will not be applied automatically to bridge.
 - no auto detection (need to setup manually every bulb with paired remote details (channel, group, type)
 - no "unreachable" state for bulbs, i believe all milight bulbs will be displayed as unreachable if milight hub get unreachable.

FUT15 is a great bulb, rich colors, solid construction and if you saw my pictures you know that i convert it to esp8266. To get 3.3v from 16v is not that easy, i try with different linear regulators, but the temp get very hot. I found is much better to power from onboard voltage regulator that output maximum 30ma. low power means low signal, but at last it will not get very hot. Last week i received my micro buck power supply and i fix also this small issue. Currently is the only bulb in my home that i know for sure it will respond fast and every time to all changes. I like ikea tradfri switches, sensors and bulbs (especially the color one) but deconz still has issues with mesh network, sometimes bulbs react with delay. Hope they will fix this with newer releases.
