### ISSUE TITLE
Amazon Alexa - Rooms not being reported to Alexa during discovery

### ISSUE THREAD

**Issue by shbatm** [mariusmotea/diyHue#76]
Hello, during my setup and attempting to move from an actual Hue Bridge to your emulated bridge, I noticed that the Hue Scenes and Hue Groups are not being reported to Alexa/Echo during Discover Devices.

Expected behavior: Alexa discovers Rooms as a device and Scenes as scenes in the Alexa app after Disabling/Re-enabling the Hue Skill.  This is how the Hue Bridge behaves.

Current behavior: Only individual lights are reported to Alexa as devices.

**Comment by mariusmotea** [comment]
Hi!

I don't have any Alexa device and for this reason is hard for me to debug this issue. Can you help me with config from your original hue bridge to compare with the one from emulator bridge?

Marius.

**Comment by shbatm** [comment]
Here's a dump of my /api/<username> from the Hue bridge.  Let me know if you need something else.
[api_username.txt](https://github.com/mariusmotea/diyHue/files/1419718/api_username.txt)

**Comment by mariusmotea** [comment]
Thanks, i will check this today and very likely commit some changes.

Marius.

**Comment by TimTower01** [comment]
Yes i think - if i have understood everything correctly - the problem is that you need the skill for the rooms and scenes. But you can only activate the skill if you have a phillips hue account wit h a connected bridge. But we cant connect the fake bridge with the myhue account due to the need of the not public remote api.

**Comment by Jhne92** [comment]
so at the moment, it is not possible to use alexa with the emulated hue bridge?
I have a real hue bridge with all my connected ZigBee lights.

Now i created a RP2 with the emulated hue bridge. Connect it to my original hue bridge.
Then i create a WS2812B (ESP8266) Hue Light Strip. And find it in the emulated hue bridge.

There is no option to find the ESP8266 in the real hue bridge or?

**Comment by TimTower01** [comment]
You can use the fake bridge with Alexa. But you have to manually add the rooms as groups. Simple discovery and on/off/dimming of the fake lights is still possible without the skill. With the scenes i am not shure. And to your question: No you cant pair the esp with the original hue bridge because it uses zigbee to communicate with the lights instead of wifi like the fakebridge and the esp.

**Comment by cheesemarathon** [comment]
Due to a lack of support for the remote API this will not work. As a work around, I suggest using a third party hub that can combine many devices and supports Alexa. For example Home Assistant.
