### ISSUE TITLE
Yeelight Support possible?

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#86]
From time to time there are some stores offering the yeelight for a good price.
It is a wifi RGBW bulb of xiami. It alrdy implements some protocol.

Is it maybe possible to integrate the yeelight into the project?

I will try to look into the raspberry code once i have more time. There exists a python library for connecting and controlling the bulbs. 

Ill take a closer look at that. Problem is im not that skilled in python (I miss the braces ) -> Im more a Java and C# guy :D 

If i get something working ill start a pull request.

**Comment by mariusmotea** [comment]
Thanks, i will help you where i have the knowledges.

**Comment by mcer12** [comment]
Hi again @mariusmotea I've been struggling to find decent RGBW bulbs as I find sonoff, milight etc really bad in terms of performance. And this issue seems extremely promising, since Yeelight are in fact wifi bulbs. Found this library, if you take a look at it that would be awesome :)
https://yeelight.readthedocs.io/en/latest/
These bulbs can be found for under 20 USD on aliexpress and they even have whole ecosystem of devices similar to the Hue. If you decide to include it in the emulator, I'll be happy to order one to help with debugging.

**Comment by mcer12** [comment]
I have no problem donating for the bulb (paypal) if you see the implementation of the api promising.

**Comment by mariusmotea** [comment]
If you live in EU i have no problem if you send the bulb to me and then i will send it back to you once i finish, but this only if shipping costs are not close to the bulb price.

**Comment by mariusmotea** [comment]
If default api is json based, i will add native support, otherwise i will use that library.

**Comment by mcer12** [comment]
I can order it from aliexpress on your address. Please give me your mail or some other way to contact you directly.

**Comment by mariusmotea** [comment]
my email address is identical with the username from here, only with an extra `.` after marius. Mail provider is gmail.

**Comment by mcer12** [comment]
Should be in your mail now.
