### ISSUE TITLE
Ideas for lightswitches? 

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#90]
This project works so great that i'm in the process of replacing a lot of lights and improving all around the house. Using Home Assistant mostly to control them, but a need for normal light switches is always there, prefreably something you build yourself and customizable is always apealing.

Also if i want to contribute some stuff to the wiki, how would one go about doing that?
This would be most apropriate as a pm to developer, but seems that github doesnt have one anymore.

**Comment by mariusmotea** [comment]
Hi,

If you want to improve the wiki you can write here or in a new issue and i can update it. I'm sure the current wiki miss lot of important informations because i develop this and everything is much simpler for me comparing with a regular user. For light switches i made a working prototype for Hue Dimmer Switch and Hue Tap Switch, but because i had no fancy case and because i don't like the idea of putting batteries in classic wall switches i start using raspbee module with Ikea tradfri switches that i consider to be both cheap and fancy.
Here you can find images of a wall switch made by another user: https://github.com/mariusmotea/diyHue/tree/master/Sensors/HueSensorStandardLightSwitch

**Comment by erazor666** [comment]
So the ikea switches will work out of the box pretty much? I'm open to buying something ready made of course, i also like to tinker and making something myself. I'm getting a 3D printer sometime, and i will experiment with some switches there. I've made a lightswitch for some mqtt controlled relay boxes i have made. Based on espeasy, they work ok. I guess one wemos can control 4-5 lights at least. They are on/off only for now. If there was an espeasy plugin that could talk to diyHue it could be some nice possibilites there.

I made some dimmers and color control pcbs that i will send the pictures and instruction for, should be helpful for other users. I will post it later today :)

**Comment by mariusmotea** [comment]
> So the ikea switches will work out of the box pretty much?

I made lot of work to have a nice integration, also tradfri bulbs are working fine. What i don't like is the raspbee module software deCONZ, still has some issues, yesterday i need to restart it because my tradfri remotes and tradfri bulbs where not working, or where working with delays, but progress is made, they push new updates fast and are promising to fix this issue.

**Comment by erazor666** [comment]
Do you have an email or some way to send the matherial? There are some pictures and i'l write some text for each, trying to make it somewhat beginner friendly and readable ;)

**Comment by mariusmotea** [comment]
Yes, same username as here, with extra `.` after marius at gmail.

**Comment by cheesemarathon** [comment]
Hi @erazor666 
Can you close this for now? Further discussions can happen over at the slack channel (link in readme).
