### ISSUE TITLE
Philips remote api

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#94]
You can request the access to the remote api here:  https://developers.meethue.com/content/remote-api 

Would be nice if the "home and return" feature would get implemented

**Comment by mariusmotea** [comment]
Ok, this is just the "public remote api". I already found information on the internet, is very close to the hue api, only that requests are sent to Philips cloud servers. What i need to know in order to made "home and return" futures is the protocol between Hue Bridge and Philips cloud servers, to implement the same. Is possible that they use custom ssl certificate, so even if i will have entire documentation on table, without the certificate i will not be able to do anything. Time is a problem for me these days, otherwise i will buy a hue bridge and try to sniff. On youtube is a guy that show to to access this device. Philips said that is possible one day to made the code public, we will see....

**Comment by Mevel** [comment]
Suggestions without Cloud Services: 
- Using some sort of Network discovery (like Nmap) to detect if a device is present.
- [Owntracks](http://owntracks.org/) To get Position Updates into MQTT Messages (iOS and Android App availabe) that can be used as Trigger within Hue Emulator

**Comment by shbatm** [comment]
Stumbled upon this implementation of the remote API, don't know if it helps any:
https://github.com/Q42/Q42.HueApi/blob/master/RemoteApi.md

**Comment by mariusmotea** [comment]
Preliminary investigation of remote communication with cloud meethue servers reveal the following http requests:

`POST /queue/getmessage?duration=180000&interval=25&sso=91c2b44e0cc2e21ed49576ab6732c15b5c8a86e5f4211feb4a1e9a086dddf9d2663e7c6b035a33b43dd98c6168842c6b8a520db62f550cd6c86c914a1970a28aba2e7d97f72a0e73df46cc6143681a2c890cd3b84ade5b7c27a28b9c6d8e8b4a8c69ab8cab5c89d3e60dd0c14d98112eeb660e51e35ff6124672b47b8836bf5b639128278b5cc4ff05b30fa751c6000a3a6c195eb33489136c40aaefd5ac08e802c691ff9e916040590bc0bbdc32560fa25e12f75bb1a2c1722346a3765b56ab&i=71e2c8c9e04ddcd9829aff9b72dccd92&auth=9b097d5ad2cc7ae083f286fee65be0281f7f833a HTTP/1.1" 200 -`

It will be required to see how these hashes are generated in order to progress forward.
Marius.

**Comment by cheesemarathon** [comment]
Closing this issue as it seems every device has a unique single sign on key to support the remote API. I think if we try and create our own keys Phillips won't be pleased and will probably start blacklisting devices/keys. If anyone has a breakthrough of some sort, then this issue can be reopened. Further chat can happen on Slack.
